### ISSUE TITLE
Always shows F:0

### ISSUE THREAD

**Issue by kuiperzone** [DarioCasciato/vscode-codequantum#3]
First off, this is useful. Thank you!

Just getting the number of lines in a project didn't seem to be something that was available until I found this.

I'm always seeing "F:0" in the footer, however, even though my files are not empty. It seems to show the number of lines in the workspace, which is primarily what I wanted. (I'm editing a C# project if that has any relevance).

Does the workspace count these include empty lines? Comments etc?

Cheers

**Comment by DarioCasciato** [comment]
Hi kuiperzone

Thanks for the feedback. It’s great to hear that you find the extension useful🙌

### Regarding "F:0" Issue
"F:0" should not appear when a file is open. I couldn’t recreate the error on my end. What is the file type you have opened, which shows you F:0? Because the extension checks a list of file types that it should count. So may be the file type you are using doesn't get count.

### Counting Lines in the Workspace
Yes, the line count includes all lines, including empty lines and comments, since there isn't a filter implemented yet. Adding an option to exclude these could be a feature for a future version.

Could you also provide:
- The version of VSCode you're using.
- The Version of the CodeQuantum extension. (Newest version: [1.2.0](https://github.com/DarioCasciato/vscode-codequantum/releases/tag/1.2.0))

Thank you for your report.

Regards
Dario

**Comment by kuiperzone** [comment]
No need. Seems to be working now. I saw the issue when first installing the plugin. I'm assuming a restart of vscode sorted it out.

Thanks for the reply.

**Comment by kuiperzone** [comment]
I've actually only got verion 1.0.1, but I am running VsCodium. Sorry, should have made that clear.

**Comment by DarioCasciato** [comment]
No Problem, Thanks for the clarification👍

Regards
Dario
